### ISSUE TITLE
[ERROR]  discord.SendAlerts: Problem with Post, status code is not 204

### ISSUE THREAD

**Issue by kolesaevagrana** [masgustavos/alertmanager-discord#3]
Hello,

Our installation stopped sending messages, but gets 
```
[ERROR]  discord.SendAlerts: Problem with Post, status code is not 204.
StatusCode: 400, Message: 400 Bad Request
```

But the same webhooks work well with curl or other test services from the same host.

![image](https://user-images.githubusercontent.com/69296097/191892883-6b8a643b-48bf-40dc-aa86-575d10e343a4.png)

Could you please point us where is our mistake? 
It was working for about 3 month, but stopped working about 3 days ago, i have just tried to stop and remove service, remove folder and make a new deploy, but there are no changes.

**Comment by viscafcb96** [comment]
I was got the same issue and figured out that the default discord's username is "alertmanager-discord", which will be included in the message body when sending to discord and resulted like the following ![Screenshot from 2022-09-27 03-42-37](https://user-images.githubusercontent.com/30786617/192376089-8120d781-013b-4490-8a76-942e474330c9.png)

I don't know why discord do not allow using the username that contains `discord` anymore.

The solution is that we can override the default username by declaring it explicitly, if you are using helm chart you can specify the username like the following
  
![Screenshot from 2022-09-27 03-45-46](https://user-images.githubusercontent.com/30786617/192376906-03295897-0da0-4b37-afb4-85db70455f05.png)

Hope this help!

**Comment by kolesaevagrana** [comment]
@Phu96 ,
Hi, 
Yep, you made my day! It helped very well!
Thanks a lot

**Comment by kolesaevagrana** [comment]
@masgustavos,
Hello,
Could you please add username into the config.example.yaml file and add some comments above it?

**Comment by masgustavos** [comment]
Hi @Phu96 and @kolesaevagrana! Sorry for the absence in this issue. Thanks for figuring it out @Phu96!!

> Could you please add username into the config.example.yaml file and add some comments above it?

Sure thing, will do.
